### PR TITLE
Proposed fix for the Linux (maybe other OSs)  issue, because of depre…

### PR DESCRIPTION
**Pull request by ebachard**
…cated CONSTANTS

Hello,

I had to fix some issues on Linux (x86_64, Mint 18.3) to make it compile. 

Just in case you fond it usefull, take the license you need, and thanks a lot for sharing your code :-)

### CODE REVIEW

**Comment by powderluv** [comment]
Thanks for the fix. It got it much further on High Sierra + ffmpeg 4. However I still see:

src/video/drivers/ffmpeg.cpp:150:14: error: out-of-line definition of 'FfmpegVideo' does not match any declaration in 'pangolin::FfmpegVideo'
FfmpegVideo::FfmpegVideo(const std::string filename, const std::string strfmtout, const std::string codec_hint, bool dump_info, int user_video_stream)
             ^~~~~~~~~~~
src/video/drivers/ffmpeg.cpp:156:19: error: out-of-line definition of 'InitUrl' does not match any declaration in 'pangolin::FfmpegVideo'
void FfmpegVideo::InitUrl(const std::string url, const std::string strfmtout, const std::string codec_hint, bool dump_info, int user_video_stream)

**Comment by powderluv** [comment]
Verified this patch works to build Pangolin on 10.13.5 and ffmpeg 4 from homebrew

**Comment by NikolausDemmel** [comment]
I can also confirm that this patch fixes compilation also for Pangolin master with ffmpeg 4 on macOS Sierra.

**Comment by TaylorDixonHD** [comment]
Confirmed that this fix works for macOS HighSierra 10.13.5

**Comment by stevenlovegrove** [comment]
Finally got around to testing this on my machine and cherry-picked as d9daba62dfa3f6c786699723621b5ca4566206dd
Thanks!

**Comment by rstoji** [comment]
I still can't build it. Still getting same errors on Ubuntu 20.04 even though this patch is in master. 

```
 error: ‘CODEC_FLAG_GLOBAL_HEADER’ was not declared in this scope; did you mean ‘AV_CODEC_FLAG_GLOBAL_HEADER’?
  519 |         stream->codec->flags |= CODEC_FLAG_GLOBAL_HEADER;

```

**Comment by marcojob** [comment]
> I still can't build it. Still getting same errors on Ubuntu 20.04 even though this patch is in master.
> 
> ```
>  error: ‘CODEC_FLAG_GLOBAL_HEADER’ was not declared in this scope; did you mean ‘AV_CODEC_FLAG_GLOBAL_HEADER’?
>   519 |         stream->codec->flags |= CODEC_FLAG_GLOBAL_HEADER;
> ```

Same here, also on Ubuntu 20.04

**Pull request closed without merging**
