### PR TITLE
Mouse Modifiers without GLUT (on windows)

### PR DESCRIPTION
**Pull request by randi120**
Hey @stevenlovegrove, 
I was developing on Ubuntu 16.04 and expanded a couple Handlers to use modifiers on mouse actions.

I was surprised to find no modifiers when I switched back to Windows 7, so I added a few that are GLUT independent. 

They follow the pattern of `glutGetModifiers`, namely CTRL, SHIFT, ALT (as bitmasks).

### CODE REVIEW

**Comment by stevenlovegrove** [comment]
Ah, I guess I didn't get around to that :), Thanks for the patch! I'll try to get this merged in after I give it a test on Windows.

**Comment by randi120** [comment]
It would be good to double check it on a system with GLUT. I think it should work :)

If it helps here a screen grab of SimpleDisplay with debug print statements on `Handle3D` SimpleDisplay

**Comment by stevenlovegrove** [comment]
Rebased! Thanks!

**Comment by randi120** [comment]
:)

**Pull request closed without merging**
