### PR TITLE
deactivate OpenNI by default

### PR DESCRIPTION
**Pull request by christian-rauch**
Reduce compile dependencies.
Can be activated again by `-DBUILD_PANGOLIN_OPENNI=ON -DBUILD_PANGOLIN_OPENNI2=ON`.

### CODE REVIEW

**Comment by stevenlovegrove** [comment]
The Pangolin ethos is generally "enable it if it's there". If you disable this by default, why not everything else?

**Comment by christian-rauch** [comment]
There are many hardware-specific dependencies in Pangolin (OpenNI, RealSense, DepthSense, TeliCam, ...) which are activated by default. It is very unlikely that a user will need all of them at once inside Pangolin. It would be more efficient to just have those enabled that a user actually uses.

This, of course, doesn't mean that these libraries can't be used manually to stream images to Pangolin.

If you still prefer to have these hardware dependencies enables by default, I will just close this PR.

**Comment by stevenlovegrove** [comment]
My view is that if people have these SDK's on their computer, it is likely that they will wish to use them with Pangolin. A compromise might be to introduce a 'NO_DEFAULT_VIDEO_DRIVERS' flag or similar to override this behaviour.

**Comment by christian-rauch** [comment]
Fair point. I am going to close this and manually deactivate the flags if I require a faster compilation.

**Pull request closed without merging**
