### PR TITLE
doc and script update

### PR DESCRIPTION
**Pull request by christian-rauch**
Small updates to the install script and documentation.

### CODE REVIEW

**Comment by stevenlovegrove** [comment]
I also prefer and use Ninja, but I don't think it's wise to suggest that in the readme as it is another dependency that can go wrong and can confuse people who haven't heard of it

**Comment by christian-rauch** [comment]
Ping @stevenlovegrove .

**Comment by christian-rauch** [comment]
The main reason for this PR is to simplify the command-line steps for building the CMake project. The Ninja steps are now optional.

I also added the simplified build instructions to the CI script. I experimented with getting the Ninja steps running in the CI, but this failed with some compilation error on Windows with OpenNI.

**Comment by christian-rauch** [comment]
@stevenlovegrove Can you have a look at this again? The Ninja build is now an optional step.

**Pull request merged**
